#!/bin/sh

# On FreeBSD:
#   pkg install autotools
#
# On Linux:
#   apt-get update
#   apt-get install autotools-dev autoconf libtool
#   or apt-get install build-essential
#
#   yum install epel-release
#   yum group install "Development Tools"
#   yum install openssl-devel zlib-devel libev-devel
#
# Git setup:
#   git init
#   git add \
#     .gitignore \
#     AUTHORS \
#     COPYING \
#     ChangeLog \
#     Makefile.am \
#     NEWS \
#     README \
#     configure.ac \
#     man/Makefile.am \
#     setup-env \
#     src/${pname}.c \
#     src/${pname}.h \
#     src/${pname}_private.h \
#     src/Makefile.am \
#     src/diag.txt \
#     test/Makefile.am \
#     test/diag.txt \
#     test/gendata.c \
#     test/runscripts \
#     test/testbar.c \
#     test/testfoo.c \
#     test/unittest.h
do_init() {
    #autoreconf --force --install
    autoreconf --force
    aclocal
    autoheader
    autoreconf
    automake --add-missing
    libtoolize
    make distclean
    autoreconf
    ./configure --prefix=$HOME --enable-debug
}

do_dev() {
    autoreconf --force
    ./configure --prefix=$HOME --enable-debug
}

do_dev_static() {
    autoreconf --force
    ./configure --prefix=$HOME --enable-debug --enable-allstatic
}

do_dev_ndebug() {
    autoreconf --force
    ./configure --prefix=$HOME
}

do_dev_ndebug_static() {
    autoreconf --force
    ./configure --prefix=$HOME --enable-allstatic --enable-lto
}


# This is a sample third party project.
#
# While it makes no harm you can safely remove it.
#
# And you can add any projects that can be integrated using GNU autotools.
# In order to do that, you have to keep in sync AC_CONFIG_SUBDIRS() macro
# in this project's configure.ac as well as SUBDIRS and DIST_SUBDIRS in
# this project's top level Makefile.am
dirs="third-party/asd ."
#dirs="third-party/mndiag third-party/mrkcommon third-party/mrkl4c ."
R=`pwd -P`

LDFLAGS=
for i in $dirs
do
    LDFLAGS="$LDFLAGS -L${R}/$i/src/.libs"
done
LDFLAGS="$LDFLAGS -L$HOME/lib -L/usr/local/lib"
export LDFLAGS

CFLAGS=
for i in $dirs
do
    CFLAGS="$CFLAGS -I${R}/$i/src"
done
CFLAGS="$CFLAGS -I$HOME/include -I/usr/local/include"
export CFLAGS

if test "$1" = "init"
then
    for i in $dirs
    do
        ( cd $i && do_init )
    done

elif test "$1" = "dev"
then
    for i in $dirs
    do
        ( cd $i && do_dev )
    done

elif test "$1" = "dev-static"
then
    for i in $dirs
    do
        ( cd $i && do_dev_static )
    done

elif test "$1" = "dev-ndebug"
then
    for i in $dirs
    do
        ( cd $i && do_dev_ndebug )
    done

elif test "$1" = "dev-ndebug-static"
then
    for i in $dirs
    do
        ( cd $i && do_dev_ndebug_static )
    done

elif test "$1" = "dist"
then
    unset LDFLAGS
    unset CFLAGS
    autoreconf --force
    ./configure

    if test -d port
    then
        if test -f port/distinfo
        then
            truncate -s0 port/distinfo
        fi
        if test -d /data2/mkushnir/distfiles
        then
            for i in *.tar.gz
            do
                cp -v $i /data2/mkushnir/distfiles/
                if test -f port/distinfo
                then
                    /sbin/sha256 $i >port/distinfo
                    echo "SIZE ($i) = `stat -f%z $i`" >>port/distinfo
                fi
            done
        fi
    fi
elif test "$1" = "du"
then
    find . -type f -name '*.[ch]' -ls | awk '{print $7;}' | (n=0; while read a; do n=$((n + a)); done; echo $n)
else
    echo "`basename $0` {init|dev[-static]|dist|dev-ndebug[-static]|du}"
fi
