#!/bin/sh


_find_sources() {
    local vars var

    vars="`grep -E -o '^[a-zA-Z0-9_]+_SOURCES' $1/Makefile.am || true`"

    if test -n "$vars"
    then
        for var in `echo $vars`
        do
            ${_MAKE_V} $var -f $1/Makefile || true
        done
    fi
}


_find_all_sources() {
    local i sources
    for i in $@
    do
        if ! test -d "$i"
        then
            echo "$i" is not a directory >&2
            exit 1
        fi

        if ! test -e "$i/Makefile.am"
        then
            echo "No such file: $i/Makefile.am" >&2
            exit 1
        fi

        if ! test -e "$i/Makefile"
        then
            echo "No such file: $i/Makefile" >&2
            exit 1
        fi

        sources="`_find_sources $i`"
        if test -n "$sources"
        then
            echo $sources | xargs -n1 -I% echo $i/%
        fi
    done
}


_gmake_v() {
    local _v
    _v=$1
    shift
    eval gmake --eval "'_mn_qwe: ; @echo \$(${_v})'" $@
}


_make_v() {
    local _v
    _v=$1
    shift
    eval make --eval "'_mn_qwe: ; @echo \$(${_v})'" $@
}


_make_p() {
    local _v
    _v=$1
    shift
    eval make -p $@ 2>/dev/null | grep "^${_v}"
}


#
# main
#
make -VQWE >/dev/null 2>&1
if test $?  -eq 0
then
    _MAKE_V="make -V"
else
    make --eval "'_mn_qwe: ;'" >/dev/null 2>&1
    if test $? -eq 0
    then
        if which gmake >/dev/null
        then
            _MAKE_V=_gmake_v
        else
            _MAKE_V=_make_v
        fi
    else
        make -p >/dev/null 2>&1
        if test $? -eq 0
        then
            _MAKE_V=_make_p
        else
            echo "cannot configure make -V, exiting ..."
            exit 1
        fi
    fi
fi

# if test "$MAKE" = gmake
# then
#     _MAKE_V=_gmake_v
# else
#     _MAKE_V="$MAKE -V"
# fi
export _MAKE_V

# All or nothing: set -e ... set +e
set -e
all_sources="`_find_all_sources $@`"
set +e
all_sources="`echo $all_sources | xargs -n1 -I% echo % | grep '.*\.c$' | sort -u`"
echo $all_sources
